import { ActionCategory, Achievement, Flora } from './types';

export const ECO_ACTIONS: ActionCategory[] = [
    {
        id: 'travel',
        labelKey: 'travel_transport',
        icon: '🚗',
        actions: [
            { id: 'walk', labelKey: 'walk', pointsPerUnit: 20, unit: 'km', max: 20, co2KgPerUnit: 0.18 },
            { id: 'cycle', labelKey: 'cycle_bike', pointsPerUnit: 20, unit: 'km', max: 50, co2KgPerUnit: 0.18 },
            { id: 'public_transport', labelKey: 'public_transport', pointsPerUnit: 15, unit: 'km', max: 100, co2KgPerUnit: 0.1 },
            { id: 'ev', labelKey: 'ev', pointsPerUnit: 5, unit: 'km', max: 200, co2KgPerUnit: 0.12 },
        ],
        bonuses: [
            { id: 'car_free_day', labelKey: 'car_free_day', points: 200, co2Kg: 5 },
            { id: 'bike_walk_week', labelKey: 'bike_walk_week', points: 500, co2Kg: 25 },
        ],
    },
    {
        id: 'food',
        labelKey: 'food_choices',
        icon: '🍲',
        actions: [
            { id: 'vegetarian', labelKey: 'vegetarian_meal', pointsPerUnit: 25, unit: 'meals', max: 5, co2KgPerUnit: 2.5 },
            { id: 'vegan', labelKey: 'vegan_meal', pointsPerUnit: 40, unit: 'meals', max: 5, co2KgPerUnit: 4 },
            { id: 'avoid_food_waste', labelKey: 'avoid_food_waste', pointsPerUnit: 20, unit: 'times', max: 5, co2KgPerUnit: 0.9 },
            { id: 'reusable_container', labelKey: 'reusable_container', pointsPerUnit: 15, unit: 'times', max: 5, co2KgPerUnit: 0.1 },
            { id: 'local_organic', labelKey: 'local_organic_produce', pointsPerUnit: 30, unit: 'meals', max: 5, co2KgPerUnit: 0.5 },
        ],
        bonuses: [
            { id: 'meatless_week', labelKey: 'meatless_week', points: 150, co2Kg: 15 },
            { id: 'zero_food_waste_week', labelKey: 'zero_food_waste_week', points: 300, co2Kg: 6 },
        ],
    },
    {
        id: 'home',
        labelKey: 'home_energy',
        icon: '🏡',
        actions: [
            { id: 'lights_off', labelKey: 'switch_off_lights', pointsPerUnit: 10, unit: 'times', max: 10, co2KgPerUnit: 0.05 },
            { id: 'no_ac', labelKey: 'no_ac_1hr', pointsPerUnit: 25, unit: 'hours', max: 8, co2KgPerUnit: 0.6 },
            { id: 'short_shower', labelKey: 'reduce_shower_5min', pointsPerUnit: 20, unit: 'times', max: 2, co2KgPerUnit: 0.2 },
        ],
        bonuses: [
            { id: 'led_upgrade', labelKey: 'led_bulb_upgrade', points: 50, co2Kg: 20 },
            { id: 'solar_panel', labelKey: 'solar_panel_use', points: 500, co2Kg: 100 },
            { id: 'earth_hour', labelKey: 'earth_hour', points: 100, co2Kg: 1 },
            { id: 'low_energy_day', labelKey: 'low_energy_day', points: 300, co2Kg: 5 },
        ],
    },
    {
        id: 'waste',
        labelKey: 'waste_lifestyle',
        icon: '🛍️',
        actions: [
            { id: 'reusable_bag', labelKey: 'cloth_reusable_bag', pointsPerUnit: 20, unit: 'times', max: 5, co2KgPerUnit: 0.05 },
            { id: 'recycle', labelKey: 'recycling_session', pointsPerUnit: 30, unit: 'sessions', max: 3, co2KgPerUnit: 1.5 },
            { id: 'compost', labelKey: 'compost_waste', pointsPerUnit: 80, unit: 'times', max: 2, co2KgPerUnit: 0.8 },
            { id: 'repair_reuse', labelKey: 'repair_reuse_item', pointsPerUnit: 60, unit: 'items', max: 3, co2KgPerUnit: 5 },
        ],
        bonuses: [
            { id: 'donate', labelKey: 'donate_clothes_books', points: 50, co2Kg: 10 },
            { id: 'zero_plastic_day', labelKey: 'zero_plastic_day', points: 200, co2Kg: 2 },
            { id: 'recycling_week', labelKey: 'recycling_week', points: 400, co2Kg: 10 },
        ],
    },
    {
        id: 'community',
        labelKey: 'community_impact',
        icon: '🌱',
        actions: [
            { id: 'share_awareness', labelKey: 'share_eco_awareness', pointsPerUnit: 30, unit: 'times', max: 5, co2KgPerUnit: 0 },
            { id: 'mentor', labelKey: 'mentor_eco_habits', pointsPerUnit: 70, unit: 'people', max: 3, co2KgPerUnit: 0 },
        ],
        bonuses: [
            { id: 'plant_tree', labelKey: 'plant_a_tree', points: 150, co2Kg: 25 },
            { id: 'join_cleanup_drive', labelKey: 'join_cleanup_drive', points: 100, co2Kg: 3 },
            { id: 'tree_plantation_drive', labelKey: 'tree_plantation_drive', points: 600, co2Kg: 250 },
            { id: 'community_cleanup_leader', labelKey: 'community_cleanup_leader', points: 800, co2Kg: 50 },
        ],
    },
];

export const ACHIEVEMENTS_LIST: Achievement[] = [
    { id: 'badge_100', nameKey: 'ach_eco_sprout_name', descriptionKey: 'ach_eco_sprout_desc', quoteKey: 'ach_eco_sprout_quote', icon: '🌱', pointsThreshold: 100, pointsAwarded: 10 },
    { id: 'badge_500', nameKey: 'ach_recycling_rookie_name', descriptionKey: 'ach_recycling_rookie_desc', quoteKey: 'ach_recycling_rookie_quote', icon: '♻️', pointsThreshold: 500, pointsAwarded: 50 },
    { id: 'badge_1000', nameKey: 'ach_green_guardian_name', descriptionKey: 'ach_green_guardian_desc', quoteKey: 'ach_green_guardian_quote', icon: '🛡️', pointsThreshold: 1000, pointsAwarded: 100 },
    { id: 'badge_2000', nameKey: 'ach_sustainability_star_name', descriptionKey: 'ach_sustainability_star_desc', quoteKey: 'ach_sustainability_star_quote', icon: '⭐', pointsThreshold: 2000, pointsAwarded: 100 },
    { id: 'badge_3000', nameKey: 'ach_climate_champion_name', descriptionKey: 'ach_climate_champion_desc', quoteKey: 'ach_climate_champion_quote', icon: '🏆', pointsThreshold: 3000, pointsAwarded: 100 },
    { id: 'badge_4000', nameKey: 'ach_eco_influencer_name', descriptionKey: 'ach_eco_influencer_desc', quoteKey: 'ach_eco_influencer_quote', icon: '📣', pointsThreshold: 4000, pointsAwarded: 100 },
    { id: 'badge_5000', nameKey: 'ach_earth_ally_name', descriptionKey: 'ach_earth_ally_desc', quoteKey: 'ach_earth_ally_quote', icon: '🤝', pointsThreshold: 5000, pointsAwarded: 200 },
    { id: 'badge_10000', nameKey: 'ach_forest_founder_name', descriptionKey: 'ach_forest_founder_desc', quoteKey: 'ach_forest_founder_quote', icon: '🌳', pointsThreshold: 10000, pointsAwarded: 500 },
    { id: 'badge_20000', nameKey: 'ach_grove_grower_name', descriptionKey: 'ach_grove_grower_desc', quoteKey: 'ach_grove_grower_quote', icon: '🌳🌳', pointsThreshold: 20000, pointsAwarded: 500 },
    { id: 'badge_30000', nameKey: 'ach_woodland_weaver_name', descriptionKey: 'ach_woodland_weaver_desc', quoteKey: 'ach_woodland_weaver_quote', icon: '🌳🌳🌳', pointsThreshold: 30000, pointsAwarded: 500 },
];

export const FLORA_LIST: Flora[] = [
    { name: 'Oak Tree', icons: ['🌱', '🌿', '🌳'] },
    { name: 'Rose Bush', icons: ['🌱', '🌿', '🌹'] },
    { name: 'Sunflower', icons: ['🌱', '🌿', '🌻'] },
    { name: 'Pine Tree', icons: ['🌱', '🌲', '🌲'] },
    { name: 'Tulip', icons: ['🌱', '🌷', '🌷'] },
    { name: 'Magic Mushroom', icons: ['🍄', '🍄', '🍄'] },
    { name: 'Hibiscus', icons: ['🌱', '🌿', '🌺'] },
    { name: 'Cactus', icons: ['🌵', '🌵', '🌵'] },
    { name: 'Lavender', icons: ['🌱', '🌿', '🌿'] },
    { name: 'Palm Tree', icons: ['🌴', '🌴', '🌴'] },
    { name: 'Cherry Blossom', icons: ['🌱', '🌳', '🌸'] },
    { name: 'Bonsai', icons: ['🎍', '🎍', '🎍'] },
];

export const COUNTRIES = [
  "India", "United States of America", "China", "Brazil", "Russia", "United Kingdom", "Canada", "Australia", "Germany", "France", "Japan",
  "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Austria", "Azerbaijan",
  "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brunei", "Bulgaria", "Burkina Faso", "Burundi",
  "Cabo Verde", "Cambodia", "Cameroon", "Central African Republic", "Chad", "Chile", "Colombia", "Comoros", "Congo, Democratic Republic of the", "Congo, Republic of the", "Costa Rica", "Cote d'Ivoire", "Croatia", "Cuba", "Cyprus", "Czechia",
  "Denmark", "Djibouti", "Dominica", "Dominican Republic",
  "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia",
  "Fiji", "Finland",
  "Gabon", "Gambia", "Georgia", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana",
  "Haiti", "Honduras", "Hungary",
  "Iceland", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy",
  "Jamaica", "Jordan",
  "Kazakhstan", "Kenya", "Kiribati", "Kosovo", "Kuwait", "Kyrgyzstan",
  "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg",
  "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar",
  "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Korea", "North Macedonia", "Norway",
  "Oman",
  "Pakistan", "Palau", "Palestine State", "Panama", "Papua new Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal",
  "Qatar",
  "Romania", "Rwanda",
  "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Korea", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria",
  "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu",
  "Uganda", "Ukraine", "United Arab Emirates", "Uruguay", "Uzbekistan",
  "Vanuatu", "Vatican City", "Venezuela", "Vietnam",
  "Yemen",
  "Zambia", "Zimbabwe"
];


export const LOCALIZATION_STRINGS = {
    en: {
        dashboard: 'Dashboard', profile: 'Profile', my_garden: 'My Garden', leaderboard: 'Leaderboard', friends: 'Friends',
        travel_transport: 'Travel & Transport', walk: 'Walk', cycle_bike: 'Cycle/Bike', public_transport: 'Public Transport', ev: 'EV', car_free_day: 'Car-Free Day', bike_walk_week: 'Bike/Walk Week',
        food_choices: 'Food Choices', vegetarian_meal: 'Vegetarian Meal', vegan_meal: 'Vegan Meal', avoid_food_waste: 'Avoid Food Waste', reusable_container: 'Reusable Bottle/Lunch Box', local_organic_produce: 'Local/Organic Produce', meatless_week: 'Meatless Week', zero_food_waste_week: 'Zero Food Waste Week',
        home_energy: 'Home & Energy', switch_off_lights: 'Switch Off Lights/Fans', no_ac_1hr: 'No A/C for 1 Hr', reduce_shower_5min: 'Reduce Shower by 5 Mins', led_bulb_upgrade: 'LED Bulb Upgrade', solar_panel_use: 'Solar Panel Use', earth_hour: 'Earth Hour', low_energy_day: 'Low Energy Day',
        waste_lifestyle: 'Waste & Lifestyle', cloth_reusable_bag: 'Cloth/Reusable Bag', recycling_session: 'Recycling Session', compost_waste: 'Compost Waste', repair_reuse_item: 'Repair/Reuse Item', donate_clothes_books: 'Donate Clothes/Books', zero_plastic_day: 'Zero Plastic Day', recycling_week: 'Recycling Week',
        community_impact: 'Community & Impact', plant_a_tree: 'Plant a Tree', join_cleanup_drive: 'Join Cleanup Drive', share_eco_awareness: 'Share Eco-Awareness', mentor_eco_habits: 'Mentor Eco-Habits', tree_plantation_drive: 'Tree Plantation Drive', community_cleanup_leader: 'Community Cleanup Leader',
        log_todays_actions: "Log Today's Actions", total_points: "Total Points", trees_planted: "Trees Planted", my_weekly_goal: "My Weekly Goal", set_your_goal: "Set your weekly points goal:", update_profile: "Update Profile",
        create_avatar: "Create Your Eco Avatar", get_eco_tip: "Get a New Eco Tip!", eco_hero: "Eco Pro", green_hero_of_the_month: "Green Hero of the Month",
        congratulations: "Congratulations!", youve_unlocked_a_new_achievement: "You've unlocked a new achievement!", share_achievement: "Share Achievement", download_certificate: "Download Certificate",
        current_streak: "Current Streak", nickname: "Nickname", lock_in_my_vibe: "Lock In My Vibe", profile_locked: "Profile Locked", unlocks_in: "Unlocks in",
        achievements: 'Achievements', daily_progress: "Today's Progress", weekly_progress: "This Week's Progress", choose_your_guardian: 'Choose Your Guardian',
        ach_eco_sprout_name: 'Eco Sprout', ach_eco_sprout_desc: 'Awarded for reaching 100 points. Your journey has begun!', ach_eco_sprout_quote: 'The journey of a thousand miles begins with a single step.',
        ach_recycling_rookie_name: 'Recycling Rookie', ach_recycling_rookie_desc: 'Awarded for reaching 500 points. You are making a difference!', ach_recycling_rookie_quote: 'Waste is not waste until we waste it.',
        ach_green_guardian_name: 'Green Guardian', ach_green_guardian_desc: 'Awarded for reaching 1,000 points. A true guardian of the green.', ach_green_guardian_quote: 'The greatest threat to our planet is the belief that someone else will save it.',
        ach_sustainability_star_name: 'Sustainability Star', ach_sustainability_star_desc: 'Awarded for reaching 2,000 points. Your consistent efforts are shining bright.', ach_sustainability_star_quote: 'We do not inherit the Earth from our ancestors; we borrow it from our children.',
        ach_climate_champion_name: 'Climate Champion', ach_climate_champion_desc: 'Awarded for reaching 3,000 points. Championing the cause for a better climate.', ach_climate_champion_quote: 'The time is always right to do what is right.',
        ach_eco_influencer_name: 'Eco Influencer', ach_eco_influencer_desc: "Awarded for reaching 4,000 points. You're inspiring others with your actions.", ach_eco_influencer_quote: 'To be a catalyst is the ambition of the environmentalist.',
        ach_earth_ally_name: 'Earth Ally', ach_earth_ally_desc: 'Awarded for reaching 5,000 points. A powerful ally for the planet.', ach_earth_ally_quote: 'The Earth has music for those who listen.',
        ach_forest_founder_name: 'Forest Founder', ach_forest_founder_desc: "10,000 points! You've planted your first tree in the garden!", ach_forest_founder_quote: 'He who plants a tree, plants a hope.',
        ach_grove_grower_name: 'Grove Grower', ach_grove_grower_desc: '20,000 points! Your second tree has been planted, creating a grove!', ach_grove_grower_quote: 'A society grows great when old men plant trees whose shade they know they shall never sit in.',
        ach_woodland_weaver_name: 'Woodland Weaver', ach_woodland_weaver_desc: '30,000 points! A third tree joins your garden, weaving a new woodland.', ach_woodland_weaver_quote: 'The creation of a thousand forests is in one acorn.',
        loading_eco_journey: "Loading Your Eco Journey...",
        welcome_back: "Welcome back, {name}!",
        ready_to_make_difference: "Ready to make a difference today?",
        eco_hero_corner: "Eco Hero's Corner",
        thinking: "Thinking...",
        logged_actions_alert: "Logged actions! You earned points today! Resetting sliders.",
        log_actions_to_see_progress: "Log actions to see your progress!",
        points: "points",
        points_earned: "Points Earned",
        welcome_banner_title: "Welcome!",
        welcome_banner_text: "Let's set up your profile and choose your guardian to get started.",
        name_label: "Name",
        country_label: "Country",
        choose_avatar_alert: "Please choose your guardian avatar before saving!",
        name_nickname_empty_alert: "Name and Nickname cannot be empty!",
        profile_updated_alert: "Profile Updated & Locked for 24 hours!",
        start_journey_button: "& Start Journey!",
        hear_eco_quote_tooltip: "Click to hear an eco quote!",
        tts_not_supported_alert: "Sorry, your browser does not support text-to-speech.",
        male: "Male",
        female: "Female",
        my_daily_eco_habits: "My Daily Eco Habits",
        set_daily_defaults_desc: "Set your typical daily actions here. They'll be used as defaults when you log.",
        garden_slogan: "Your garden grows with your eco actions. Keep it up!",
        plants_earned: "Plants Earned",
        next_plant_in: "Next Plant In",
        farmer_tooltip: "Your friendly farmer!",
        garden_is_seed_title: "Your garden is just a seed.",
        garden_is_seed_desc: "Reach 10000 points to unlock your first tree!",
        drag_and_drop_info: "Drag and drop your plants to arrange your garden!",
        leaderboard_slogan: "See who's leading the charge in making a difference!",
        global: "Global",
        friends_slogan: "Connect with your friends and inspire each other!",
        add_a_friend: "Add a Friend",
        enter_friend_name_placeholder: "Enter friend's name",
        add_button: "Add",
        add_friend_simulation_note: "Note: This is a simulation. Adding a friend will generate a random user.",
        day_streak: "{value} day streak",
        plus_10_points: "+10 Points!",
        mystery_box_opened: "Mystery Box Opened!",
        found_bonus_inside: "You found a bonus inside!",
        awesome_button: "Awesome!",
        continue_button: "Continue",
        share_achievement_title: "FUTURE GAURDIAN Achievement!",
        share_achievement_text: `I just unlocked the "{achievementName}" achievement in FUTURE GAURDIAN! 🌳 Come join me in making a difference! #FutureGuardian #GoGreen`,
        achievement_copied_alert: "Achievement text copied to clipboard! Share it with your friends.",
        share_failed_alert: "Could not share achievement.",
        co2_emissions_prevented: "CO₂ Emissions Prevented",
        generating_image: "Generating image...",
        new_badge_unlocked: 'New Badge Unlocked',
        click_to_see: 'Click to view',
        dismiss: 'Dismiss',
    },
    ta: {
        dashboard: 'முதன்மை பக்கம்', profile: 'சுயவிவரம்', my_garden: 'என் தோட்டம்', leaderboard: 'தலைவர் பலகை', friends: 'நண்பர்கள்',
        travel_transport: 'பயணம் மற்றும் போக்குவரத்து', walk: 'நடைபயிற்சி', cycle_bike: 'மிதிவண்டி', public_transport: 'பொது போக்குவரத்து', ev: 'மின்சார வாகனம்', car_free_day: 'கார் இல்லாத நாள்', bike_walk_week: 'மிதிவண்டி/நடை வாரம்',
        food_choices: 'உணவு தேர்வுகள்', vegetarian_meal: 'சைவ உணவு', vegan_meal: 'நனிசைவ உணவு', avoid_food_waste: 'உணவு வீணாவதை தவிர்த்தல்', reusable_container: 'மறுபயன்பாட்டு பாட்டில்', local_organic_produce: 'உள்ளூர்/இயற்கை பொருட்கள்', meatless_week: 'மாமிசம் இல்லாத வாரம்', zero_food_waste_week: 'பூஜ்ஜிய உணவு கழிவு வாரம்',
        home_energy: 'வீடு மற்றும் ஆற்றல்', switch_off_lights: 'விளக்குகள்/விசிறிகளை அணைத்தல்', no_ac_1hr: '1 மணிநேரம் ஏசி இல்லை', reduce_shower_5min: 'குளியலை 5 நிமிடங்கள் குறைத்தல்', led_bulb_upgrade: 'LED விளக்கு மேம்பாடு', solar_panel_use: 'சூரிய சக்தி பயன்பாடு', earth_hour: 'புவி நேரம்', low_energy_day: 'குறைந்த ஆற்றல் நாள்',
        waste_lifestyle: 'கழிவு மற்றும் வாழ்க்கைமுறை', cloth_reusable_bag: 'துணி/மறுபயன்பாட்டு பை', recycling_session: 'மறுசுழற்சி', compost_waste: 'கழிவுகளை உரமாக மாற்றுதல்', repair_reuse_item: 'பழுதுபார்த்து பயன்படுத்துதல்', donate_clothes_books: 'ஆடை/புத்தகங்கள் தானம்', zero_plastic_day: 'நெகிழி இல்லாத நாள்', recycling_week: 'மறுசுழற்சி வாரம்',
        community_impact: 'சமூக தாக்கம்', plant_a_tree: 'மரம் நடுதல்', join_cleanup_drive: 'தூய்மைப் பணியில் சேரவும்', share_eco_awareness: 'சுற்றுச்சூழல் விழிப்புணர்வு பகிர்தல்', mentor_eco_habits: 'சுற்றுச்சூழல் பழக்க வழிகாட்டி', tree_plantation_drive: 'மரக்கன்று நடும் விழா', community_cleanup_leader: 'சமூக தூய்மைப் பணி தலைவர்',
        log_todays_actions: 'இன்றைய செயல்களைப் பதிவு செய்யவும்', total_points: "மொத்த புள்ளிகள்", trees_planted: "நடப்பட்ட மரங்கள்", my_weekly_goal: "எனது வாராந்திர இலக்கு", set_your_goal: "வாராந்திர புள்ளி இலக்கை அமைக்கவும்:", update_profile: "சுயவிவரத்தைப் புதுப்பிக்கவும்",
        create_avatar: "உங்கள் சுற்றுச்சூழல் பாதுகாவலரை உருவாக்கவும்", get_eco_tip: "புதிய சுற்றுச்சூழல் குறிப்பு பெறவும்!", eco_hero: "சுற்றுச்சூழல் நிபுணர்", green_hero_of_the_month: "மாதத்தின் பசுமை நாயகன்",
        congratulations: "வாழ்த்துக்கள்!", youve_unlocked_a_new_achievement: "புதிய சாதனையைத் திறந்துள்ளீர்கள்!", share_achievement: "சாதனையைப் பகிரவும்", download_certificate: "சான்றிதழைப் பதிவிறக்கவும்",
        current_streak: "தற்போதைய தொடர்", nickname: "புனைப்பெயர்", lock_in_my_vibe: "சுயவிவரத்தை பூட்டவும்", profile_locked: "சுயவிவரம் பூட்டப்பட்டது", unlocks_in: "திறக்கும் நேரம்",
        achievements: 'சாதனைகள்', daily_progress: "இன்றைய முன்னேற்றம்", weekly_progress: "இந்த வார முன்னேற்றம்", choose_your_guardian: 'உங்கள் பாதுகாவலரைத் தேர்ந்தெடுக்கவும்',
        ach_eco_sprout_name: 'சுற்றுச்சூழல் முளை', ach_eco_sprout_desc: '100 புள்ளிகளை எட்டியதற்காக வழங்கப்பட்டது. உங்கள் பயணம் தொடங்கியுள்ளது!', ach_eco_sprout_quote: 'ஆயிரம் மைல் பயணம் ஒரு అడుగుతోనే మొదలవుతుంది.',
        ach_recycling_rookie_name: 'மறுசுழற்சி வீரர்', ach_recycling_rookie_desc: '500 புள்ளிகளை எட்டியதற்காக வழங்கப்பட்டது. நீங்கள் ஒரு மாற்றத்தை உருவாக்குகிறீர்கள்!', ach_recycling_rookie_quote: 'நாம் வீணடிக்கும் வரை கழிவு கழிவு அல்ல.',
        ach_green_guardian_name: 'பசுமை பாதுகாவலர்', ach_green_guardian_desc: '1,000 புள்ளிகளை அடைந்ததற்காக வழங்கப்பட்டது. நீங்கள் பசுமையின் உண்மையான பாதுகாவலர்.', ach_green_guardian_quote: 'நமது கிரகத்திற்கு மிகப்பெரிய அச்சுறுத்தல் என்னவென்றால், வேறு யாராவது அதைக் காப்பாற்றுவார்கள் என்ற நம்பிக்கைதான்.',
        ach_sustainability_star_name: 'நிலைத்தன்மை நட்சத்திரம்', ach_sustainability_star_desc: '2,000 புள்ளிகளை அடைந்ததற்காக வழங்கப்பட்டது. உங்கள் தொடர்ச்சியான முயற்சிகள் பிரகாசிக்கின்றன.', ach_sustainability_star_quote: 'பூமியை நாம் நம் முன்னோர்களிடமிருந்து பெறவில்லை; நாம் அதை நம் குழந்தைகளிடமிருந்து கடன் வாங்குகிறோம்.',
        ach_climate_champion_name: 'காலநிலை சாம்பியன்', ach_climate_champion_desc: '3,000 புள்ளிகளை அடைந்ததற்காக வழங்கப்பட்டது. சிறந்த காலநிலைக்காக போராடும் πρωταθλητής.', ach_climate_champion_quote: 'சரியானதைச் செய்ய நேரம் எப்போதும் சரியானது.',
        ach_eco_influencer_name: 'சுற்றுச்சூழல் செல்வாக்கு செலுத்துபவர்', ach_eco_influencer_desc: '4,000 புள்ளிகளை அடைந்ததற்காக வழங்கப்பட்டது. உங்கள் செயல்களால் மற்றவர்களை ஊக்குவிக்கிறீர்கள்.', ach_eco_influencer_quote: 'ஒரு வினையூக்கியாக இருப்பது சுற்றுச்சூழலியலாளரின் லட்சியம்.',
        ach_earth_ally_name: 'பூமி நட்பு', ach_earth_ally_desc: '5,000 புள்ளிகளை அடைந்ததற்காக வழங்கப்பட்டது. கிரகத்திற்கு ஒரு சக்திவாய்ந்த நட்பு.', ach_earth_ally_quote: 'கேட்பவர்களுக்கு பூமியில் இசை உண்டு.',
        ach_forest_founder_name: 'வன நிறுவனர்', ach_forest_founder_desc: '10,000 புள்ளிகள்! உங்கள் தோட்டத்தில் உங்கள் முதல் மரத்தை நட்டுள்ளீர்கள்!', ach_forest_founder_quote: 'ஒரு மரத்தை நடுபவன், ஒரு நம்பிக்கையை விதைக்கிறான்.',
        ach_grove_grower_name: 'தோப்பு வளர்ப்பவர்', ach_grove_grower_desc: '20,000 புள்ளிகள்! உங்கள் இரண்டாவது மரம் நடப்பட்டு, ஒரு தோப்பு உருவாகிறது!', ach_grove_grower_quote: 'முதியவர்கள் தாங்கள் நிழலில் அமர முடியாத மரங்களை நடும்போது ஒரு சமூகம் சிறப்படைகிறது.',
        ach_woodland_weaver_name: 'வனப்பகுதி நெசவாளர்', ach_woodland_weaver_desc: '30,000 புள்ளிகள்! மூன்றாவது மரம் உங்கள் தோட்டத்தில் சேர்ந்து, ஒரு புதிய வனப்பகுதியை நெசவு செய்கிறது.', ach_woodland_weaver_quote: 'ஆயிரம் காடுகளின் உருவாக்கம் ஒரு கருவாலிக்கொட்டையில் உள்ளது.',
        loading_eco_journey: "உங்கள் சுற்றுச்சூழல் பயணத்தை ஏற்றுகிறது...",
        welcome_back: "மீண்டும் வருக, {name}!",
        ready_to_make_difference: "இன்று ஒரு மாற்றத்தை ஏற்படுத்தத் தயாரா?",
        eco_hero_corner: "சுற்றுச்சூழல் நாயகன் பகுதி",
        thinking: "சிந்திக்கிறது...",
        logged_actions_alert: "செயல்கள் பதிவு செய்யப்பட்டன! இன்று நீங்கள் புள்ளிகளைப் பெற்றீர்கள்! ஸ்லைடர்கள் மீட்டமைக்கப்படுகின்றன.",
        log_actions_to_see_progress: "உங்கள் முன்னேற்றத்தைக் காண செயல்களைப் பதிவு செய்யுங்கள்!",
        points: "புள்ளிகள்",
        points_earned: "பெற்ற புள்ளிகள்",
        welcome_banner_title: "நல்வரவு!",
        welcome_banner_text: "தொடங்குவதற்கு உங்கள் சுயவிவரத்தை அமைத்து உங்கள் பாதுகாவலரைத் தேர்ந்தெடுப்போம்.",
        name_label: "பெயர்",
        country_label: "நாடு",
        choose_avatar_alert: "சேமிக்கும் முன் உங்கள் பாதுகாவலர் அவதாரத்தைத் தேர்ந்தெடுக்கவும்!",
        name_nickname_empty_alert: "பெயர் மற்றும் புனைப்பெயர் காலியாக இருக்க முடியாது!",
        profile_updated_alert: "சுயவிவரம் புதுப்பிக்கப்பட்டு 24 மணிநேரத்திற்கு பூட்டப்பட்டது!",
        start_journey_button: "& பயணத்தைத் தொடங்குங்கள்!",
        hear_eco_quote_tooltip: "சுற்றுச்சூழல் மேற்கோளைக் கேட்க கிளிக் செய்க!",
        tts_not_supported_alert: "மன்னிக்கவும், உங்கள் உலாவி உரையை பேச்சாக மாற்றுவதை ஆதரிக்கவில்லை.",
        male: "ஆண்",
        female: "பெண்",
        my_daily_eco_habits: "எனது தினசரி சுற்றுச்சூழல் பழக்கங்கள்",
        set_daily_defaults_desc: "உங்கள் வழக்கமான தினசரி செயல்களை இங்கே அமைக்கவும். நீங்கள் பதிவு செய்யும் போது அவை இயல்புநிலைகளாகப் பயன்படுத்தப்படும்.",
        garden_slogan: "உங்கள் சுற்றுச்சூழல் செயல்களால் உங்கள் தோட்டம் வளர்கிறது. தொடருங்கள்!",
        plants_earned: "சம்பாதித்த செடிகள்",
        next_plant_in: "அடுத்த செடி வர",
        farmer_tooltip: "உங்கள் நட்பு விவசாயி!",
        garden_is_seed_title: "உங்கள் தோட்டம் ஒரு விதை மட்டுமே.",
        garden_is_seed_desc: "உங்கள் முதல் மரத்தைத் திறக்க 10000 புள்ளிகளை அடையுங்கள்!",
        drag_and_drop_info: "உங்கள் தோட்டத்தை ஏற்பாடு செய்ய உங்கள் செடிகளை இழுத்து விடுங்கள்!",
        leaderboard_slogan: "ஒரு மாற்றத்தை ஏற்படுத்துவதில் யார் முன்னணியில் இருக்கிறார்கள் என்று பாருங்கள்!",
        global: "உலகளாவிய",
        friends_slogan: "உங்கள் நண்பர்களுடன் இணைந்து ஒருவருக்கொருவர் ஊக்கமளியுங்கள்!",
        add_a_friend: "நண்பரைச் சேர்க்கவும்",
        enter_friend_name_placeholder: "நண்பரின் பெயரை உள்ளிடவும்",
        add_button: "சேர்",
        add_friend_simulation_note: "குறிப்பு: இது ஒரு உருவகப்படுத்துதல். நண்பரைச் சேர்ப்பது ஒரு சீரற்ற பயனரை உருவாக்கும்.",
        day_streak: "{value} நாள் தொடர்ச்சி",
        plus_10_points: "+10 புள்ளிகள்!",
        mystery_box_opened: "மர்மப் பெட்டி திறக்கப்பட்டது!",
        found_bonus_inside: "உள்ளே ஒரு போனஸ் கிடைத்தது!",
        awesome_button: "அற்புதம்!",
        continue_button: "தொடர்க",
        share_achievement_title: "FUTURE GAURDIAN சாதனை!",
        share_achievement_text: `நான் FUTURE GAURDIAN இல் "{achievementName}" சாதனையைத் திறந்துள்ளேன்! 🌳 என்னுடன் இணைந்து ஒரு மாற்றத்தை ஏற்படுத்துங்கள்! #FutureGuardian #GoGreen`,
        achievement_copied_alert: "சாதனை உரை கிளிப்போர்டுக்கு நகலெடுக்கப்பட்டது! அதை உங்கள் நண்பர்களுடன் பகிர்ந்து கொள்ளுங்கள்.",
        share_failed_alert: "சாதனையைப் பகிர முடியவில்லை.",
        co2_emissions_prevented: "CO₂ உமிழ்வுகள் தடுக்கப்பட்டன",
        generating_image: "படத்தை உருவாக்குகிறது...",
        new_badge_unlocked: 'புதிய பேட்ஜ் திறக்கப்பட்டது',
        click_to_see: 'பார்க்க கிளிக் செய்யவும்',
        dismiss: 'நீக்கு',
    },
    hi: {
        dashboard: 'डैशबोर्ड', profile: 'प्रोफ़ाइल', my_garden: 'मेरा बगीचा', leaderboard: 'लीडरबोर्ड', friends: 'दोस्त',
        travel_transport: 'यात्रा और परिवहन', walk: 'पैदल चलना', cycle_bike: 'साइकिल/बाइक', public_transport: 'सार्वजनिक परिवहन', ev: 'ईवी', car_free_day: 'कार-मुक्त दिन', bike_walk_week: 'बाइक/पैदल सप्ताह',
        food_choices: 'भोजन विकल्प', vegetarian_meal: 'शाकाहारी भोजन', vegan_meal: 'वीगन भोजन', avoid_food_waste: 'भोजन की बर्बादी से बचें', reusable_container: 'पुन: प्रयोज्य बोतल', local_organic_produce: 'स्थानीय/जैविक उत्पाद', meatless_week: 'मांस रहित सप्ताह', zero_food_waste_week: 'शून्य खाद्य अपशिष्ट सप्ताह',
        home_energy: 'घर और ऊर्जा', switch_off_lights: 'लाइट/पंखे बंद करें', no_ac_1hr: '1 घंटे के लिए एसी नहीं', reduce_shower_5min: 'शॉवर 5 मिनट कम करें', led_bulb_upgrade: 'एलईडी बल्ब अपग्रेड', solar_panel_use: 'सौर पैनल का उपयोग', earth_hour: 'अर्थ आवर', low_energy_day: 'कम ऊर्जा दिवस',
        waste_lifestyle: 'अपशिष्ट और जीवनशैली', cloth_reusable_bag: 'कपड़ा/पुन: प्रयोज्य बैग', recycling_session: 'रीसाइक्लिंग सत्र', compost_waste: 'कचरे की खाद बनाना', repair_reuse_item: 'मरम्मत/पुन: उपयोग करें', donate_clothes_books: 'कपड़े/किताबें दान करें', zero_plastic_day: 'शून्य प्लास्टिक दिवस', recycling_week: 'रीसाइक्लिंग सप्ताह',
        community_impact: 'सामुदायिक प्रभाव', plant_a_tree: 'एक पेड़ लगाओ', join_cleanup_drive: 'सफाई अभियान में शामिल हों', share_eco_awareness: 'पर्यावरण-जागरूकता साझा करें', mentor_eco_habits: 'पर्यावरण-आदतों का मार्गदर्शन करें', tree_plantation_drive: 'वृक्षारпо अभियान', community_cleanup_leader: 'सामुदायिक सफाई नेता',
        log_todays_actions: 'आज के कार्यों को लॉग करें', total_points: "कुल अंक", trees_planted: "लगाए गए पेड़", my_weekly_goal: "मेरा साप्ताहिक लक्ष्य", set_your_goal: "अपना साप्ताहिक अंक लक्ष्य निर्धारित करें:", update_profile: "प्रोफ़ाइल अपडेट करें",
        create_avatar: "अपना पर्यावरण संरक्षक बनाएं", get_eco_tip: "एक नया इको टिप प्राप्त करें!", eco_hero: "इको विशेषज्ञ", green_hero_of_the_month: "महीने का ग्रीन हीरो",
        congratulations: "बधाई हो!", youve_unlocked_a_new_achievement: "आपने एक नई उपलब्धि हासिल की है!", share_achievement: "उपलब्धि साझा करें", download_certificate: "प्रमाणपत्र डाउनलोड करें",
        current_streak: "वर्तमान स्ट्रीक", nickname: "उपनाम", lock_in_my_vibe: "प्रोफ़ाइल लॉक करें", profile_locked: "प्रोफ़ाइल लॉक है", unlocks_in: "इसमें अनलॉक होता है",
        achievements: 'उपलब्धियां', daily_progress: "आज की प्रगति", weekly_progress: "इस सप्ताह की प्रगति", choose_your_guardian: 'अपना संरक्षक चुनें',
        ach_eco_sprout_name: 'इको अंकुर', ach_eco_sprout_desc: '100 अंक तक पहुंचने के लिए सम्मानित किया गया। आपकी यात्रा शुरू हो गई है!', ach_eco_sprout_quote: 'हजारों मील की यात्रा एक कदम से शुरू होती है।',
        ach_recycling_rookie_name: 'रीसाइक्लिंग रूकी', ach_recycling_rookie_desc: '500 अंक तक पहुंचने के लिए सम्मानित किया गया। आप एक बदलाव ला रहे हैं!', ach_recycling_rookie_quote: 'कचरा तब तक कचरा नहीं है जब तक हम उसे बर्बाद न करें।',
        ach_green_guardian_name: 'हरित संरक्षक', ach_green_guardian_desc: '1,000 अंक तक पहुंचने के लिए सम्मानित किया गया। आप हरे-भरे के सच्चे संरक्षक हैं।', ach_green_guardian_quote: 'हमारे ग्रह के लिए सबसे बड़ा खतरा यह विश्वास है कि कोई और इसे बचाएगा।',
        ach_sustainability_star_name: 'सस्टेनेबिलिटी स्टार', ach_sustainability_star_desc: '2,000 अंक तक पहुंचने के लिए सम्मानित किया गया। आपके निरंतर प्रयास चमक रहे हैं।', ach_sustainability_star_quote: 'हम पृथ्वी को अपने पूर्वजों से विरासत में नहीं पाते; हम इसे अपने बच्चों से उधार लेते हैं।',
        ach_climate_champion_name: 'जलवायु चैंपियन', ach_climate_champion_desc: '3,000 अंक तक पहुंचने के लिए सम्मानित किया गया। बेहतर जलवायु के लिए कारण का समर्थन करना।', ach_climate_champion_quote: 'सही काम करने का समय हमेशा सही होता है।',
        ach_eco_influencer_name: 'इको इन्फ्लुएंसर', ach_eco_influencer_desc: '4,000 अंक तक पहुंचने के लिए सम्मानित किया गया। आप अपने कार्यों से दूसरों को प्रेरित कर रहे हैं।', ach_eco_influencer_quote: 'एक उत्प्रेरक बनना पर्यावरणविद की महत्वाकांक्षा है।',
        ach_earth_ally_name: 'पृथ्वी सहयोगी', ach_earth_ally_desc: '5,000 अंक तक पहुंचने के लिए सम्मानित किया गया। ग्रह के लिए एक शक्तिशाली सहयोगी।', ach_earth_ally_quote: 'जो सुनते हैं उनके लिए पृथ्वी के पास संगीत है।',
        ach_forest_founder_name: 'वन संस्थापक', ach_forest_founder_desc: '10,000 अंक! आपने बगीचे में अपना पहला पेड़ लगाया है!', ach_forest_founder_quote: 'जो एक पेड़ लगाता है, वह एक आशा बोता है।',
        ach_grove_grower_name: 'उपवन उत्पादक', ach_grove_grower_desc: '20,000 अंक! आपका दूसरा पेड़ लगाया गया है, जिससे एक उपवन बन रहा है!', ach_grove_grower_quote: 'एक समाज तब महान बनता है जब बूढ़े लोग ऐसे पेड़ लगाते हैं जिनकी छाया में वे कभी नहीं बैठेंगे।',
        ach_woodland_weaver_name: 'वनभूमि बुनकर', ach_woodland_weaver_desc: '30,000 अंक! एक तीसरा पेड़ आपके बगीचे में शामिल होता है, जो एक नई वनभूमि बुनता है।', ach_woodland_weaver_quote: 'हजारों जंगलों का निर्माण एक बलूत के फल में होता है।',
        loading_eco_journey: "आपकी पर्यावरण यात्रा लोड हो रही है...",
        welcome_back: "वापस स्वागत है, {name}!",
        ready_to_make_difference: "आज एक बदलाव लाने के लिए तैयार हैं?",
        eco_hero_corner: "इको हीरो का कोना",
        thinking: "सोच रहा है...",
        logged_actions_alert: "कार्यों को लॉग किया गया! आज आपने अंक अर्जित किए! स्लाइडर्स रीसेट हो रहे हैं।",
        log_actions_to_see_progress: "अपनी प्रगति देखने के लिए कार्यों को लॉग करें!",
        points: "अंक",
        points_earned: "अर्जित अंक",
        welcome_banner_title: "आपका स्वागत है!",
        welcome_banner_text: "आइए अपनी प्रोफ़ाइल सेट करें और आरंभ करने के लिए अपना संरक्षक चुनें।",
        name_label: "नाम",
        country_label: "देश",
        choose_avatar_alert: "सहेजने से पहले कृपया अपना संरक्षक अवतार चुनें!",
        name_nickname_empty_alert: "नाम और उपनाम खाली नहीं हो सकते!",
        profile_updated_alert: "प्रोफ़ाइल अपडेट की गई और 24 घंटे के लिए लॉक कर दी गई!",
        start_journey_button: "& यात्रा शुरू करें!",
        hear_eco_quote_tooltip: "एक पर्यावरण उद्धरण सुनने के लिए क्लिक करें!",
        tts_not_supported_alert: "क्षमा करें, आपका ब्राउज़र टेक्स्ट-टू-स्पीच का समर्थन नहीं करता है।",
        male: "पुरुष",
        female: "महिला",
        my_daily_eco_habits: "मेरी दैनिक पर्यावरण आदतें",
        set_daily_defaults_desc: "अपने विशिष्ट दैनिक कार्यों को यहां सेट करें। जब आप लॉग इन करेंगे तो वे डिफ़ॉल्ट के रूप में उपयोग किए जाएंगे।",
        garden_slogan: "आपके पर्यावरण कार्यों के साथ आपका बगीचा बढ़ता है। इसे जारी रखें!",
        plants_earned: "अर्जित पौधे",
        next_plant_in: "अगला पौधा इसमें",
        farmer_tooltip: "आपका मित्रवत किसान!",
        garden_is_seed_title: "आपका बगीचा सिर्फ एक बीज है।",
        garden_is_seed_desc: "अपना पहला पेड़ अनलॉक करने के लिए 10000 अंक तक पहुंचें!",
        drag_and_drop_info: "अपने बगीचे को व्यवस्थित करने के लिए अपने पौधों को खींचें और छोड़ें!",
        leaderboard_slogan: "देखें कि बदलाव लाने में कौन सबसे आगे है!",
        global: "वैश्विक",
        friends_slogan: "अपने दोस्तों से जुड़ें और एक-दूसरे को प्रेरित करें!",
        add_a_friend: "एक दोस्त जोड़ें",
        enter_friend_name_placeholder: "मित्र का नाम दर्ज करें",
        add_button: "जोड़ें",
        add_friend_simulation_note: "ध्यान दें: यह एक अनुकरण है। एक मित्र जोड़ने से एक यादृच्छिक उपयोगकर्ता उत्पन्न होगा।",
        day_streak: "{value} दिन की स्ट्रीक",
        plus_10_points: "+10 अंक!",
        mystery_box_opened: "रहस्य बॉक्स खोला गया!",
        found_bonus_inside: "आपको अंदर एक बोनस मिला!",
        awesome_button: "बहुत बढ़िया!",
        continue_button: "जारी रखें",
        share_achievement_title: "FUTURE GAURDIAN उपलब्धि!",
        share_achievement_text: `मैंने FUTURE GAURDIAN में "{achievementName}" उपलब्धि अनलॉक की है! 🌳 मेरे साथ जुड़कर एक बदलाव लाएं! #FutureGuardian #GoGreen`,
        achievement_copied_alert: "उपलब्धि पाठ क्लिपबोर्ड पर कॉपी किया गया! इसे अपने दोस्तों के साथ साझा करें।",
        share_failed_alert: "उपलब्धि साझा नहीं की जा सकी।",
        co2_emissions_prevented: "CO₂ उत्सर्जन रोका गया",
        generating_image: "छवि बना रहा है...",
        new_badge_unlocked: 'नया बैज अनलॉक हुआ',
        click_to_see: 'देखने के लिए क्लिक करें',
        dismiss: 'खारिज करें',
    },
};

export const ECO_QUOTES = [
    "The Earth does not belong to us: we belong to the Earth.",
    "Heal the earth, heal our future.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "Small acts, when multiplied by millions of people, can transform the world.",
    "Be the change you wish to see in the world... and on the planet.",
];